/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoFisica;

import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author PC
 */
public class VistaMruV extends javax.swing.JFrame {

    /**
     * Creates new form VistaMru
     */
    Mruv mruv;
    double simulacion=1;
     private Timer timer;
     TimerTask timerTask ;
    public VistaMruV() {
        initComponents();
        mruv=new Mruv();
         timer=new Timer();
        
        timerTask = new TimerTask() 
     { 
         public void run()  
         { 
           if(lblCarro.getX()<=700){
               
             lblCarro.setLocation(lblCarro.getX()+10, lblCarro.getY());
              
           }else{    
                btnCalcular.setEnabled(true);
           timer.cancel();
           }
         
         } 
     };
          timer.scheduleAtFixedRate(timerTask, 0, Math.abs((int)(1000/simulacion)));
      
        btnCalcular.setEnabled(false);
        txtDistancia.setEnabled(false);
        txtVelocidadI.setEnabled(false);
        txtTiempo.setEnabled(false);
        txtVelocidadF.setEnabled(false);
        txtAceleracion.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Calculos = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtVelocidadI = new javax.swing.JTextField();
        txtTiempo = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDistancia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rbtnVelocidadF = new javax.swing.JRadioButton();
        rbtnTiempo = new javax.swing.JRadioButton();
        rbtnDistancia = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        txtAceleracion = new javax.swing.JTextField();
        rbtnAceleracion = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtVelocidadF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        lblCarro = new javax.swing.JLabel();
        lblPlano = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Velocidad inicial");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 86, -1, -1));

        jLabel2.setText("Tiempo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 121, -1, -1));

        txtVelocidadI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVelocidadIKeyTyped(evt);
            }
        });
        getContentPane().add(txtVelocidadI, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 133, -1));

        txtTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiempoActionPerformed(evt);
            }
        });
        txtTiempo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTiempoKeyTyped(evt);
            }
        });
        getContentPane().add(txtTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 133, -1));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 345, -1, -1));

        jLabel3.setText("Resultado");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 371, -1, -1));

        lblResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 178, 35));

        jLabel5.setText("m/s");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 48, -1));

        jLabel6.setText("s");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        jLabel7.setText("Distancia");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 161, -1, -1));

        txtDistancia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDistanciaKeyTyped(evt);
            }
        });
        getContentPane().add(txtDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 133, -1));

        jLabel8.setText("m");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        jLabel9.setText("Calcular");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 30, -1, -1));

        Calculos.add(rbtnVelocidadF);
        rbtnVelocidadF.setText("Velocidad final");
        rbtnVelocidadF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnVelocidadFActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnVelocidadF, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        Calculos.add(rbtnTiempo);
        rbtnTiempo.setText("Tiempo");
        rbtnTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTiempoActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        Calculos.add(rbtnDistancia);
        rbtnDistancia.setText("Distancia");
        rbtnDistancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDistanciaActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        jLabel10.setText("Acelerción");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 211, -1, -1));

        txtAceleracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAceleracionActionPerformed(evt);
            }
        });
        txtAceleracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAceleracionKeyTyped(evt);
            }
        });
        getContentPane().add(txtAceleracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 133, -1));

        Calculos.add(rbtnAceleracion);
        rbtnAceleracion.setText("Aceleración");
        rbtnAceleracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAceleracionActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnAceleracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        jLabel4.setText("Velocidad final");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 259, -1, -1));

        txtVelocidadF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVelocidadFKeyTyped(evt);
            }
        });
        getContentPane().add(txtVelocidadF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 141, -1));

        jLabel11.setText("m/s");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 48, -1));

        jLabel12.setText("m/s^2");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home_house_3526.png"))); // NOI18N
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, -1, -1));

        lblCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diagram-61_24456.png"))); // NOI18N
        getContentPane().add(lblCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        lblPlano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.PNG"))); // NOI18N
        getContentPane().add(lblPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asdfghhl.jpg"))); // NOI18N
        jLabel13.setText("jLabel4");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiempoActionPerformed

    private void rbtnDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDistanciaActionPerformed
           txtDistancia.setEnabled(false);
           txtVelocidadI.setEnabled(true);
           txtVelocidadF.setEnabled(true);
           txtTiempo.setEnabled(true);
           txtAceleracion.setEnabled(true);
           btnCalcular.setEnabled(true);
           vaciar();
    }//GEN-LAST:event_rbtnDistanciaActionPerformed

    private void rbtnVelocidadFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnVelocidadFActionPerformed
        btnCalcular.setEnabled(true);
        txtDistancia.setEnabled(false);
        txtVelocidadI.setEnabled(true);
        txtTiempo.setEnabled(true);
        txtVelocidadF.setEnabled(false);
        txtAceleracion.setEnabled(true);
        vaciar();
    }//GEN-LAST:event_rbtnVelocidadFActionPerformed

    private void rbtnTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTiempoActionPerformed
         btnCalcular.setEnabled(true);
        txtDistancia.setEnabled(false);
        txtVelocidadI.setEnabled(true);
        txtTiempo.setEnabled(false);
        txtVelocidadF.setEnabled(true);
        txtAceleracion.setEnabled(true);
        vaciar();
    }//GEN-LAST:event_rbtnTiempoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
       Double resultado=0.0;
        if(rbtnDistancia.isSelected()==true){
            simulacion=5;
           resultado=mruv.calcularDistancia( Double.parseDouble(txtVelocidadI.getText()),Double.parseDouble(txtVelocidadF.getText()),
                    Double.parseDouble(txtTiempo.getText()));
           
           lblResultado.setText(""+resultado+" metros");
        }
       if(rbtnVelocidadF.isSelected()==true){
           simulacion=Double.parseDouble(txtAceleracion.getText());
            resultado=mruv.calcularVelocidadFinal(Double.parseDouble(txtVelocidadI.getText()),simulacion,
                    Double.parseDouble(txtTiempo.getText()));
              System.out.println(resultado);
           lblResultado.setText(""+resultado+" metros/segundos");
           
          }
       
            if(rbtnTiempo.isSelected()==true){
                simulacion=Double.parseDouble(txtAceleracion.getText());
            resultado=mruv.calcularTiempo(Double.parseDouble(txtVelocidadI.getText()),  Double.parseDouble(txtVelocidadF.getText()),
                    simulacion);
           lblResultado.setText(""+resultado+" segundos");
            }
            
              if(rbtnAceleracion.isSelected()==true){
            resultado=mruv.calcularAceleracion(Double.parseDouble(txtVelocidadI.getText()),  Double.parseDouble(txtVelocidadF.getText()),
                    Double.parseDouble(txtTiempo.getText()));
            simulacion=resultado;
           lblResultado.setText(""+resultado+" segundos");
            }
              timer=new Timer();
                timerTask = new TimerTask() 
     { 
         public void run()  
         { 
           if(lblCarro.getX()<=700){
               
             lblCarro.setLocation(lblCarro.getX()+10, lblCarro.getY());
              
           }else{    
                btnCalcular.setEnabled(true);
           timer.cancel();
           }
         
         } 
     };
            timer.scheduleAtFixedRate(timerTask, 0, Math.abs((int)(1000/(simulacion+1))));
      
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtVelocidadIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVelocidadIKeyTyped
         char c=evt.getKeyChar(); 
             
         
          if(Character.isDigit(c)==false) { 
              
               if(c!='.'){
                    evt.consume(); 
                getToolkit().beep();
               }
               
          } 
    }//GEN-LAST:event_txtVelocidadIKeyTyped

    private void txtTiempoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTiempoKeyTyped
       char c=evt.getKeyChar(); 
             
         
          if(Character.isDigit(c)==false) { 
              
               if(c!='.'){
                    evt.consume(); 
                getToolkit().beep();
               }
               
          } 
    }//GEN-LAST:event_txtTiempoKeyTyped

    private void txtDistanciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDistanciaKeyTyped
       char c=evt.getKeyChar(); 
             
         
          if(Character.isDigit(c)==false) { 
              
               if(c!='.'){
                    evt.consume(); 
                getToolkit().beep();
               }
               
          } 
    }//GEN-LAST:event_txtDistanciaKeyTyped
       public void vaciar(){
         
        txtDistancia.setText("");
        txtVelocidadI.setText("");
        txtTiempo.setText("");
        txtVelocidadF.setText("");
        txtAceleracion.setText("");
        lblResultado.setText("");
       }
    private void txtAceleracionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAceleracionKeyTyped
        char c=evt.getKeyChar(); 
             
         
          if(Character.isDigit(c)==false) { 
              
               if(c!='.'){
                    evt.consume(); 
                getToolkit().beep();
               }
               
           
    }            
    }//GEN-LAST:event_txtAceleracionKeyTyped

    private void rbtnAceleracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAceleracionActionPerformed
        btnCalcular.setEnabled(true);
        txtDistancia.setEnabled(false);
        txtVelocidadI.setEnabled(true);
        txtTiempo.setEnabled(true);
        txtVelocidadF.setEnabled(true);
        txtAceleracion.setEnabled(false);
        vaciar();
    }//GEN-LAST:event_rbtnAceleracionActionPerformed

    private void txtVelocidadFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVelocidadFKeyTyped
        char c=evt.getKeyChar(); 
             
         
          if(Character.isDigit(c)==false) { 
              
               if(c!='.'){
                    evt.consume(); 
                getToolkit().beep();
               }
               
     } 
              
    }//GEN-LAST:event_txtVelocidadFKeyTyped

    private void txtAceleracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAceleracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAceleracionActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMruV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMruV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMruV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMruV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMruV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup Calculos;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCarro;
    private javax.swing.JLabel lblPlano;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JRadioButton rbtnAceleracion;
    private javax.swing.JRadioButton rbtnDistancia;
    private javax.swing.JRadioButton rbtnTiempo;
    private javax.swing.JRadioButton rbtnVelocidadF;
    private javax.swing.JTextField txtAceleracion;
    private javax.swing.JTextField txtDistancia;
    private javax.swing.JTextField txtTiempo;
    private javax.swing.JTextField txtVelocidadF;
    private javax.swing.JTextField txtVelocidadI;
    // End of variables declaration//GEN-END:variables
}
