/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoFisica;

import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class VistaMcu extends javax.swing.JFrame {
     private Mcu mcu;
    /**
     * Creates new form mcu
     */
     private Timer timer;
     private double velocidad;
     private double g=0;
    
    public VistaMcu() {
        initComponents();
        mcu=new Mcu();
         timer=new Timer();
        btnCalcular.setEnabled(false);
        txtAngulo.setEnabled(false);
        txtVelocidadAngular.setEnabled(false);
        txtTiempo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtVelocidadAngular = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rbtnTiempo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bntNuevo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtAngulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        txtTiempo = new javax.swing.JTextField();
        rbtnVelocidad = new javax.swing.JRadioButton();
        btnCalcular = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        rbtnDistancia = new javax.swing.JRadioButton();
        lblCarro = new javax.swing.JLabel();
        lblPlano = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtVelocidadAngular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVelocidadAngularKeyTyped(evt);
            }
        });
        getContentPane().add(txtVelocidadAngular, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 90, 169, -1));

        jLabel9.setText("Calcular");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 37, -1, -1));

        buttonGroup1.add(rbtnTiempo);
        rbtnTiempo.setText("Tiempo");
        rbtnTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTiempoActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 29, -1, -1));

        jLabel5.setText("radianes/s");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 93, -1, -1));

        jLabel8.setText("grados");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 172, -1, -1));

        bntNuevo.setText("Nuevo calculo");
        bntNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(bntNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 375, -1, -1));

        jLabel6.setText("s");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 130, -1, -1));

        lblResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 307, 178, 35));

        jLabel2.setText("Tiempo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 132, -1, -1));

        jLabel1.setText("Velocidad Angular");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 93, -1, -1));

        txtAngulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnguloKeyTyped(evt);
            }
        });
        getContentPane().add(txtAngulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 169, 169, -1));

        jLabel3.setText("Resultado");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 317, -1, -1));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home_house_3526.png"))); // NOI18N
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 357, -1, -1));

        txtTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiempoActionPerformed(evt);
            }
        });
        txtTiempo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTiempoKeyTyped(evt);
            }
        });
        getContentPane().add(txtTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 127, 169, -1));

        buttonGroup1.add(rbtnVelocidad);
        rbtnVelocidad.setText("Velocidad Angular");
        rbtnVelocidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnVelocidadActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 29, -1, -1));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 227, -1, -1));

        jLabel7.setText("Angulo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 168, -1, -1));

        buttonGroup1.add(rbtnDistancia);
        rbtnDistancia.setText("Angulo");
        rbtnDistancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDistanciaActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 29, -1, -1));

        lblCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diagram-61_24456.png"))); // NOI18N
        getContentPane().add(lblCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, -1, -1));

        lblPlano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.PNG"))); // NOI18N
        getContentPane().add(lblPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asdfghhl.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTiempoActionPerformed

        txtTiempo.setEnabled(false);
        txtVelocidadAngular.setEnabled(true);

        txtAngulo.setEnabled(true);
        btnCalcular.setEnabled(true);
        vaciar();
    }//GEN-LAST:event_rbtnTiempoActionPerformed

    private void bntNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntNuevoActionPerformed
        rbtnVelocidad.setEnabled(true);
        rbtnTiempo.setEnabled(true);
        rbtnDistancia.setEnabled(true);
        txtTiempo.setEditable(true);
        txtVelocidadAngular.setEditable(true);
        txtAngulo.setEditable(true);
    }//GEN-LAST:event_bntNuevoActionPerformed

    private void txtVelocidadAngularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVelocidadAngularKeyTyped
        char c=evt.getKeyChar();

        if(Character.isDigit(c)==false) {

            if(c!='.'){
                evt.consume();
                getToolkit().beep();
            }

        }
    }//GEN-LAST:event_txtVelocidadAngularKeyTyped

    private void txtAnguloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnguloKeyTyped
        char c=evt.getKeyChar();

        if(Character.isDigit(c)==false) {

            if(c!='.'){
                evt.consume();
                getToolkit().beep();
            }

        }
    }//GEN-LAST:event_txtAnguloKeyTyped

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void txtTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiempoActionPerformed

    private void txtTiempoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTiempoKeyTyped
        char c=evt.getKeyChar();

        if(Character.isDigit(c)==false) {

            if(c!='.'){
                evt.consume();
                getToolkit().beep();
            }

        }
    }//GEN-LAST:event_txtTiempoKeyTyped

    private void rbtnVelocidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnVelocidadActionPerformed

        txtVelocidadAngular.setEnabled(false);
        txtTiempo.setEnabled(true);
        txtAngulo.setEnabled(true);
        btnCalcular.setEnabled(true);
        vaciar();
    }//GEN-LAST:event_rbtnVelocidadActionPerformed
    public void deshabilitar(){
            rbtnVelocidad.setEnabled(false);
       rbtnTiempo.setEnabled(false);
       rbtnDistancia.setEnabled(false);
       txtTiempo.setEditable(false);
       txtVelocidadAngular.setEditable(false);
       txtAngulo.setEditable(false);
     }
        public void vaciar(){
         txtTiempo.setText("");
         txtVelocidadAngular.setText("");
         txtAngulo.setText("");
          lblResultado.setText(" ");
    }
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        double resultado=0.0;
        double velocidad=0.0;
        try{
            deshabilitar();

            if(txtAngulo.isEnabled()==false){
                velocidad=Double.parseDouble(txtVelocidadAngular.getText());
                resultado=mcu.calcularAngulo( Double.parseDouble(txtTiempo.getText()),velocidad);
                lblResultado.setText(""+resultado+" grados");
            }
            if(txtVelocidadAngular.isEnabled()==false){

                resultado=mcu.calcularVelocidadAngular( mcu.gradosARadianes(Double.parseDouble(txtAngulo.getText())),Double.parseDouble(txtTiempo.getText()));
                velocidad=resultado;
                lblResultado.setText(""+resultado+" radianes/segundos");
            }
            if(txtTiempo.isEnabled()==false){
                velocidad=Double.parseDouble(txtVelocidadAngular.getText());
                resultado=mcu.calcularTiempo( mcu.gradosARadianes(Double.parseDouble(txtAngulo.getText())),velocidad);

                lblResultado.setText(""+resultado+" segundos");
            }
              TimerTask timerTask = new TimerTask() 
     { 
         public void run()  
         { 
           if(g < 2 * Math.PI){
               
             lblCarro.setLocation((int)(+45+Math.abs(50 * (float)Math.cos(g)+100)),(int)(50+ Math.abs(50 * (float)Math.sin(g)+100)));
               System.out.println(lblCarro.getLocation());
               g += (float)Math.PI/12;
           }else{    
                btnCalcular.setEnabled(true);
                 timer.cancel();
           }
         
         } 
     };
              timer=new Timer();
          timer.scheduleAtFixedRate(timerTask, 0, Math.abs((int)(100/velocidad)));
            

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error de ingreso de datos");
        }

    }//GEN-LAST:event_btnCalcularActionPerformed

    private void rbtnDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDistanciaActionPerformed

        txtAngulo.setEnabled(false);
        txtVelocidadAngular.setEnabled(true);
        txtTiempo.setEnabled(true);
        btnCalcular.setEnabled(true);
        vaciar();
    }//GEN-LAST:event_rbtnDistanciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMcu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntNuevo;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnMenu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCarro;
    private javax.swing.JLabel lblPlano;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JRadioButton rbtnDistancia;
    private javax.swing.JRadioButton rbtnTiempo;
    private javax.swing.JRadioButton rbtnVelocidad;
    private javax.swing.JTextField txtAngulo;
    private javax.swing.JTextField txtTiempo;
    private javax.swing.JTextField txtVelocidadAngular;
    // End of variables declaration//GEN-END:variables
}
