/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoFisica;

import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class VistaMovParabolico extends javax.swing.JFrame {
    private MovParabolico mP;
    /**
     * Creates new form VistaMovParabolico
     */
    public VistaMovParabolico() {
        initComponents();
         mP=new MovParabolico();
        
        btnCalcular.setEnabled(false);
        txtDistancia.setEnabled(false);
        txtVelocidadAngular.setEnabled(false);
        txtAngulo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtVelocidadAngular = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bntNuevo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAngulo = new javax.swing.JTextField();
        btnMenu = new javax.swing.JButton();
        txtDistancia = new javax.swing.JTextField();
        rbtnVelocidad = new javax.swing.JRadioButton();
        btnCalcular = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        rbtnDistancia = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtVelocidadAngular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVelocidadAngularKeyTyped(evt);
            }
        });
        getContentPane().add(txtVelocidadAngular, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 100, -1));

        jLabel9.setText("Calcular");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel5.setText("metros/s");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        jLabel8.setText("grados");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        bntNuevo.setText("Nuevo calculo");
        bntNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(bntNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        jLabel6.setText("metros");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 100, -1));

        lblResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 210, 30));

        jLabel1.setText("Velocidad Angular");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel2.setText("Distancia");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel3.setText("Resultado");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        txtAngulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnguloKeyTyped(evt);
            }
        });
        getContentPane().add(txtAngulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 100, -1));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home_house_3526.png"))); // NOI18N
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, -1, -1));

        txtDistancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDistanciaActionPerformed(evt);
            }
        });
        txtDistancia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDistanciaKeyTyped(evt);
            }
        });
        getContentPane().add(txtDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 100, -1));

        rbtnVelocidad.setText("Velocidad Angular");
        rbtnVelocidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnVelocidadActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jLabel7.setText("Angulo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        rbtnDistancia.setText("Distancia");
        rbtnDistancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDistanciaActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asdfghhl.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVelocidadAngularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVelocidadAngularKeyTyped
        char c=evt.getKeyChar();

        if(Character.isDigit(c)==false) {

            if(c!='.'){
                evt.consume();
                getToolkit().beep();
            }

        }
    }//GEN-LAST:event_txtVelocidadAngularKeyTyped

    private void bntNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntNuevoActionPerformed
        rbtnVelocidad.setEnabled(true);
        
        rbtnDistancia.setEnabled(true);
        txtDistancia.setEditable(true);
        txtVelocidadAngular.setEditable(true);
        txtAngulo.setEditable(true);
    }//GEN-LAST:event_bntNuevoActionPerformed

    private void txtAnguloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnguloKeyTyped
        char c=evt.getKeyChar();

        if(Character.isDigit(c)==false) {

            if(c!='.'){
                evt.consume();
                getToolkit().beep();
            }

        }
    }//GEN-LAST:event_txtAnguloKeyTyped

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void txtDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDistanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDistanciaActionPerformed

    private void txtDistanciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDistanciaKeyTyped
        char c=evt.getKeyChar();

        if(Character.isDigit(c)==false) {

            if(c!='.'){
                evt.consume();
                getToolkit().beep();
            }

        }
    }//GEN-LAST:event_txtDistanciaKeyTyped

    private void rbtnVelocidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnVelocidadActionPerformed

        txtVelocidadAngular.setEnabled(false);
        txtDistancia.setEnabled(true);
        txtAngulo.setEnabled(true);
        btnCalcular.setEnabled(true);
        vaciar();
    }//GEN-LAST:event_rbtnVelocidadActionPerformed
 public void deshabilitar(){
            rbtnVelocidad.setEnabled(false);
      
       rbtnDistancia.setEnabled(false);
       txtDistancia.setEditable(false);
       txtVelocidadAngular.setEditable(false);
       txtAngulo.setEditable(false);
     }
        public void vaciar(){
         txtDistancia.setText("");
         txtVelocidadAngular.setText("");
         txtAngulo.setText("");
          lblResultado.setText(" ");
    }
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        double resultado=0.0;
        double velocidad=0.0;
        try{
            deshabilitar();

           
            if(txtVelocidadAngular.isEnabled()==false){
                double radianes=mP.gradosARadianes(Double.parseDouble(txtAngulo.getText()));
                resultado=mP.calcularVelocidad(radianes,Double.parseDouble(txtDistancia.getText()));
                velocidad=resultado;
                lblResultado.setText(""+resultado+" metros/segundos");
            }
            if(txtDistancia.isEnabled()==false){
                    double radianes=mP.gradosARadianes(Double.parseDouble(txtAngulo.getText()));
                velocidad=Double.parseDouble(txtVelocidadAngular.getText());
                resultado=mP.calcularDistancia(Double.parseDouble(txtVelocidadAngular.getText()),radianes);

                lblResultado.setText(""+resultado+" metros");
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error de ingreso de datos");
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void rbtnDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDistanciaActionPerformed

        txtAngulo.setEnabled(true);
        txtVelocidadAngular.setEnabled(true);
        txtDistancia.setEnabled(false);
        btnCalcular.setEnabled(true);
        vaciar();
    }//GEN-LAST:event_rbtnDistanciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMovParabolico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMovParabolico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMovParabolico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMovParabolico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMovParabolico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntNuevo;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JRadioButton rbtnDistancia;
    private javax.swing.JRadioButton rbtnVelocidad;
    private javax.swing.JTextField txtAngulo;
    private javax.swing.JTextField txtDistancia;
    private javax.swing.JTextField txtVelocidadAngular;
    // End of variables declaration//GEN-END:variables
}
