/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mru;

import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class VistaMcu extends javax.swing.JFrame {
     private Mcu mcu;
    /**
     * Creates new form mcu
     */
    public VistaMcu() {
        initComponents();
        mcu=new Mcu();
        btnCalcular.setEnabled(false);
        txtAngulo.setEnabled(false);
        txtVelocidadAngular.setEnabled(false);
        txtTiempo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtVelocidadAngular = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rbtnTiempo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bntNuevo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtAngulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        txtTiempo = new javax.swing.JTextField();
        rbtnVelocidad = new javax.swing.JRadioButton();
        btnCalcular = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        rbtnDistancia = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtVelocidadAngular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVelocidadAngularKeyTyped(evt);
            }
        });

        jLabel9.setText("Calcular");

        buttonGroup1.add(rbtnTiempo);
        rbtnTiempo.setText("Tiempo");
        rbtnTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTiempoActionPerformed(evt);
            }
        });

        jLabel5.setText("radianes/s");

        jLabel8.setText("grados");

        bntNuevo.setText("Nuevo calculo");
        bntNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNuevoActionPerformed(evt);
            }
        });

        jLabel6.setText("s");

        lblResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Tiempo");

        jLabel1.setText("Velocidad Angular");

        txtAngulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnguloKeyTyped(evt);
            }
        });

        jLabel3.setText("Resultado");

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mru/home_house_3526.png"))); // NOI18N
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        txtTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiempoActionPerformed(evt);
            }
        });
        txtTiempo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTiempoKeyTyped(evt);
            }
        });

        buttonGroup1.add(rbtnVelocidad);
        rbtnVelocidad.setText("Velocidad Angular");
        rbtnVelocidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnVelocidadActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jLabel7.setText("Angulo");

        buttonGroup1.add(rbtnDistancia);
        rbtnDistancia.setText("Angulo");
        rbtnDistancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDistanciaActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mru/asdfghhl.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(rbtnVelocidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnTiempo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnDistancia))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAngulo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)))))
                .addContainerGap(466, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txtVelocidadAngular, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(jLabel5))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(610, 610, 610)
                            .addComponent(bntNuevo))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(jLabel9))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(180, 180, 180)
                            .addComponent(btnCalcular))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(750, 750, 750)
                            .addComponent(btnMenu))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jLabel7))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnVelocidad)
                    .addComponent(rbtnTiempo)
                    .addComponent(rbtnDistancia))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtAngulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(240, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(83, 83, 83)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtVelocidadAngular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel5))))
                            .addGap(16, 16, 16)
                            .addComponent(jLabel2)
                            .addGap(223, 223, 223)
                            .addComponent(bntNuevo))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jLabel9))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(310, 310, 310)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(220, 220, 220)
                            .addComponent(btnCalcular))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(350, 350, 350)
                            .addComponent(btnMenu))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(161, 161, 161)
                            .addComponent(jLabel7))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(300, 300, 300)
                            .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTiempoActionPerformed

        txtTiempo.setEnabled(false);
        txtVelocidadAngular.setEnabled(true);

        txtAngulo.setEnabled(true);
        btnCalcular.setEnabled(true);
        vaciar();
    }//GEN-LAST:event_rbtnTiempoActionPerformed

    private void bntNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntNuevoActionPerformed
        rbtnVelocidad.setEnabled(true);
        rbtnTiempo.setEnabled(true);
        rbtnDistancia.setEnabled(true);
        txtTiempo.setEditable(true);
        txtVelocidadAngular.setEditable(true);
        txtAngulo.setEditable(true);
    }//GEN-LAST:event_bntNuevoActionPerformed

    private void txtVelocidadAngularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVelocidadAngularKeyTyped
        char c=evt.getKeyChar();

        if(Character.isDigit(c)==false) {

            if(c!='.'){
                evt.consume();
                getToolkit().beep();
            }

        }
    }//GEN-LAST:event_txtVelocidadAngularKeyTyped

    private void txtAnguloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnguloKeyTyped
        char c=evt.getKeyChar();

        if(Character.isDigit(c)==false) {

            if(c!='.'){
                evt.consume();
                getToolkit().beep();
            }

        }
    }//GEN-LAST:event_txtAnguloKeyTyped

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void txtTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiempoActionPerformed

    private void txtTiempoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTiempoKeyTyped
        char c=evt.getKeyChar();

        if(Character.isDigit(c)==false) {

            if(c!='.'){
                evt.consume();
                getToolkit().beep();
            }

        }
    }//GEN-LAST:event_txtTiempoKeyTyped

    private void rbtnVelocidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnVelocidadActionPerformed

        txtVelocidadAngular.setEnabled(false);
        txtTiempo.setEnabled(true);
        txtAngulo.setEnabled(true);
        btnCalcular.setEnabled(true);
        vaciar();
    }//GEN-LAST:event_rbtnVelocidadActionPerformed
    public void deshabilitar(){
            rbtnVelocidad.setEnabled(false);
       rbtnTiempo.setEnabled(false);
       rbtnDistancia.setEnabled(false);
       txtTiempo.setEditable(false);
       txtVelocidadAngular.setEditable(false);
       txtAngulo.setEditable(false);
     }
        public void vaciar(){
         txtTiempo.setText("");
         txtVelocidadAngular.setText("");
         txtAngulo.setText("");
          lblResultado.setText(" ");
    }
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        double resultado=0.0;
        double velocidad=0.0;
        try{
            deshabilitar();

            if(txtAngulo.isEnabled()==false){
                velocidad=Double.parseDouble(txtVelocidadAngular.getText());
                resultado=mcu.calcularAngulo( Double.parseDouble(txtTiempo.getText()),velocidad);
                lblResultado.setText(""+resultado+" grados");
            }
            if(txtVelocidadAngular.isEnabled()==false){

                resultado=mcu.calcularVelocidadAngular( mcu.gradosARadianes(Double.parseDouble(txtAngulo.getText())),Double.parseDouble(txtTiempo.getText()));
                velocidad=resultado;
                lblResultado.setText(""+resultado+" radianes/segundos");
            }
            if(txtTiempo.isEnabled()==false){
                velocidad=Double.parseDouble(txtVelocidadAngular.getText());
                resultado=mcu.calcularTiempo( mcu.gradosARadianes(Double.parseDouble(txtAngulo.getText())),velocidad);

                lblResultado.setText(""+resultado+" segundos");
            }
            

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error de ingreso de datos");
        }

    }//GEN-LAST:event_btnCalcularActionPerformed

    private void rbtnDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDistanciaActionPerformed

        txtAngulo.setEnabled(false);
        txtVelocidadAngular.setEnabled(true);
        txtTiempo.setEnabled(true);
        btnCalcular.setEnabled(true);
        vaciar();
    }//GEN-LAST:event_rbtnDistanciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMcu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntNuevo;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnMenu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JRadioButton rbtnDistancia;
    private javax.swing.JRadioButton rbtnTiempo;
    private javax.swing.JRadioButton rbtnVelocidad;
    private javax.swing.JTextField txtAngulo;
    private javax.swing.JTextField txtTiempo;
    private javax.swing.JTextField txtVelocidadAngular;
    // End of variables declaration//GEN-END:variables
}
