/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mru;

import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author PC
 */
public class VistaMru extends javax.swing.JFrame {

    /**
     * Creates new form VistaMru
     */
    private Mru mru;
    private Timer timer;
    public VistaMru() {
        initComponents();
        mru=new Mru();
        timer=new Timer();
        btnCalcular.setEnabled(false);
        txtDistancia.setEnabled(false);
           txtVelocidad.setEnabled(false);
            txtTiempo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Calculos = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtVelocidad = new javax.swing.JTextField();
        txtTiempo = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDistancia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rbtnVelocidad = new javax.swing.JRadioButton();
        rbtnTiempo = new javax.swing.JRadioButton();
        rbtnDistancia = new javax.swing.JRadioButton();
        lblCarro = new javax.swing.JLabel();
        lblPlano = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Velocidad");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 86, -1, -1));

        jLabel2.setText("Tiempo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 121, -1, -1));

        txtVelocidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVelocidadKeyTyped(evt);
            }
        });
        getContentPane().add(txtVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 83, 169, -1));

        txtTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiempoActionPerformed(evt);
            }
        });
        txtTiempo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTiempoKeyTyped(evt);
            }
        });
        getContentPane().add(txtTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 118, 169, -1));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        jLabel3.setText("Resultado");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        lblResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 178, 35));

        jLabel5.setText("m/s");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 86, -1, -1));

        jLabel6.setText("s");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 121, -1, -1));

        jLabel7.setText("Distancia");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 161, -1, -1));

        txtDistancia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDistanciaKeyTyped(evt);
            }
        });
        getContentPane().add(txtDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 158, 169, -1));

        jLabel8.setText("m");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 161, -1, -1));

        jLabel9.setText("Calcular");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 30, -1, -1));

        Calculos.add(rbtnVelocidad);
        rbtnVelocidad.setText("Velocidad");
        rbtnVelocidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnVelocidadActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 30, -1, -1));

        Calculos.add(rbtnTiempo);
        rbtnTiempo.setText("Tiempo");
        rbtnTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTiempoActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 30, -1, -1));

        Calculos.add(rbtnDistancia);
        rbtnDistancia.setText("Distancia");
        rbtnDistancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDistanciaActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 30, -1, -1));

        lblCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mru/diagram-61_24456.png"))); // NOI18N
        getContentPane().add(lblCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        lblPlano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mru/fondo.PNG"))); // NOI18N
        getContentPane().add(lblPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mru/asdfghhl.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiempoActionPerformed

    private void rbtnDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDistanciaActionPerformed
       
        txtDistancia.setEnabled(false);
           txtVelocidad.setEnabled(true);
            txtTiempo.setEnabled(true);
            btnCalcular.setEnabled(true);
             vaciar();
    }//GEN-LAST:event_rbtnDistanciaActionPerformed

    private void rbtnVelocidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnVelocidadActionPerformed
        
        txtVelocidad.setEnabled(false);
         txtTiempo.setEnabled(true);
            txtDistancia.setEnabled(true);
            btnCalcular.setEnabled(true);
            vaciar();
    }//GEN-LAST:event_rbtnVelocidadActionPerformed

    private void rbtnTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTiempoActionPerformed
         
        txtTiempo.setEnabled(false);
           txtVelocidad.setEnabled(true);

            txtDistancia.setEnabled(true);
            btnCalcular.setEnabled(true);
             vaciar();
    }//GEN-LAST:event_rbtnTiempoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
       
        double resultado=0.0;
       double velocidad=0.0;
       lblCarro.setLocation(400, lblCarro.getY());
       
      TimerTask timerTask = new TimerTask() 
     { 
         public void run()  
         { 
           if(lblCarro.getX()<=700){
               btnCalcular.setEnabled(false);
             lblCarro.setLocation(lblCarro.getX()+10, lblCarro.getY());
              
           }else{    
                btnCalcular.setEnabled(true);
           timer.cancel();
           }
         
         } 
     };
    
        if(txtDistancia.isEnabled()==false){
           velocidad=Double.parseDouble(txtVelocidad.getText());
           resultado=mru.calcularDistancia( Double.parseDouble(txtTiempo.getText()),velocidad);
           lblResultado.setText(""+resultado+" metros");
       }
          if(txtVelocidad.isEnabled()==false){
          
           resultado=mru.calcularVelocidad( Double.parseDouble(txtDistancia.getText()),Double.parseDouble(txtTiempo.getText()));
           velocidad=resultado;
           lblResultado.setText(""+resultado+" metros/segundos");
       }
            if(txtTiempo.isEnabled()==false){
            velocidad=Double.parseDouble(txtVelocidad.getText());
           resultado=mru.calcularTiempo( Double.parseDouble(txtDistancia.getText()),velocidad);
        
           lblResultado.setText(""+resultado+" segundos");
       }
             timer=new Timer();  
     timer.scheduleAtFixedRate(timerTask, 0, Math.abs((int)(1000/velocidad)));
      
           
    }//GEN-LAST:event_btnCalcularActionPerformed
    public void vaciar(){
         txtTiempo.setText("");
         txtVelocidad.setText("");
         txtDistancia.setText("");
          lblResultado.setText(" ");
    }
    private void txtVelocidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVelocidadKeyTyped
         char c=evt.getKeyChar(); 
             
         
          if(Character.isDigit(c)==false) { 
              
               if(c!='.'){
                    evt.consume(); 
                getToolkit().beep();
               }
               
          } 
    }//GEN-LAST:event_txtVelocidadKeyTyped

    private void txtTiempoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTiempoKeyTyped
       char c=evt.getKeyChar(); 
             
         
          if(Character.isDigit(c)==false) { 
              
               if(c!='.'){
                    evt.consume(); 
                getToolkit().beep();
               }
               
          } 
    }//GEN-LAST:event_txtTiempoKeyTyped

    private void txtDistanciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDistanciaKeyTyped
       char c=evt.getKeyChar(); 
             
         
          if(Character.isDigit(c)==false) { 
              
               if(c!='.'){
                    evt.consume(); 
                getToolkit().beep();
               }
               
          } 
    }//GEN-LAST:event_txtDistanciaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup Calculos;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCarro;
    private javax.swing.JLabel lblPlano;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JRadioButton rbtnDistancia;
    private javax.swing.JRadioButton rbtnTiempo;
    private javax.swing.JRadioButton rbtnVelocidad;
    private javax.swing.JTextField txtDistancia;
    private javax.swing.JTextField txtTiempo;
    private javax.swing.JTextField txtVelocidad;
    // End of variables declaration//GEN-END:variables
}
